name: server_app
description: A server app using the shelf package and Docker.
version: 1.0.0
repository: https://github.com/Ramzes5614/server_app

environment:
  sdk: ^3.4.4

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  sqflite: ^2.3.3+1

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
